#include "message.h"

const char* opcode_names[16] = {
    [OPCODE_QUERY] = "OPCODE_QUERY",
    [OPCODE_IQUERY] = "OPCODE_IQUERY",
    [OPCODE_STATUS] = "OPCODE_STATUS",
    [OPCODE_RESERVED0] = "OPCODE_RESERVED0",
    [OPCODE_RESERVED1] = "OPCODE_RESERVED1",
    [OPCODE_RESERVED2] = "OPCODE_RESERVED2",
    [OPCODE_RESERVED3] = "OPCODE_RESERVED3",
    [OPCODE_RESERVED4] = "OPCODE_RESERVED4",
    [OPCODE_RESERVED5] = "OPCODE_RESERVED5",
    [OPCODE_RESERVED6] = "OPCODE_RESERVED6",
    [OPCODE_RESERVED7] = "OPCODE_RESERVED7",
    [OPCODE_RESERVED8] = "OPCODE_RESERVED8",
    [OPCODE_RESERVED9] = "OPCODE_RESERVED9",
    [OPCODE_RESERVED10] = "OPCODE_RESERVED10",
    [OPCODE_RESERVED11] = "OPCODE_RESERVED11",
    [OPCODE_RESERVED12] = "OPCODE_RESERVED12",
};

const char* rcode_names[16] = {
    [RCODE_NO_ERROR] = "RCODE_NO_ERROR",
    [RCODE_FORMAT_ERROR] = "RCODE_FORMAT_ERROR",
    [RCODE_SERVER_FAILURE] = "RCODE_SERVER_FAILURE",
    [RCODE_NAME_ERROR] = "RCODE_NAME_ERROR",
    [RCODE_NOT_IMPLEMENTED] = "RCODE_NOT_IMPLEMENTED",
    [RCODE_REFUSED] = "RCODE_REFUSED",
    [RCODE_RESERVED0] = "RCODE_RESERVED0",
    [RCODE_RESERVED1] = "RCODE_RESERVED1",
    [RCODE_RESERVED2] = "RCODE_RESERVED2",
    [RCODE_RESERVED3] = "RCODE_RESERVED3",
    [RCODE_RESERVED4] = "RCODE_RESERVED4",
    [RCODE_RESERVED5] = "RCODE_RESERVED5",
    [RCODE_RESERVED6] = "RCODE_RESERVED6",
    [RCODE_RESERVED7] = "RCODE_RESERVED7",
    [RCODE_RESERVED8] = "RCODE_RESERVED8",
    [RCODE_RESERVED9] = "RCODE_RESERVED9",
};
